#!/usr/bin/env bash
# PreToolUse(Edit|Write|MultiEdit): block hand-edits to Payload-generated files.
set -euo pipefail

input=$(cat)
file=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')

case "$file" in
  */payload-types.ts)
    echo "Blocked: payload-types.ts is generated by Payload. Do not edit it by hand. Regenerate with: pnpm nx run @tee-backoffice/cms:generate:types" >&2
    exit 2
    ;;
  */importMap.js)
    echo "Blocked: importMap.js is generated by Payload. Do not edit it by hand. Regenerate with: pnpm generate:importmap" >&2
    exit 2
    ;;
esac

exit 0
