export interface GeographicAreaFixture {
  inseeCode: string
  name: string
  coverageType: 'region' | 'departement'
  parentInseeCode?: string
  isOverseas?: boolean
}

export const REGIONS: GeographicAreaFixture[] = [
  { inseeCode: '11', name: 'Île-de-France', coverageType: 'region' },
  { inseeCode: '24', name: 'Centre-Val de Loire', coverageType: 'region' },
  { inseeCode: '27', name: 'Bourgogne-Franche-Comté', coverageType: 'region' },
  { inseeCode: '28', name: 'Normandie', coverageType: 'region' },
  { inseeCode: '32', name: 'Hauts-de-France', coverageType: 'region' },
  { inseeCode: '44', name: 'Grand Est', coverageType: 'region' },
  { inseeCode: '52', name: 'Pays de la Loire', coverageType: 'region' },
  { inseeCode: '53', name: 'Bretagne', coverageType: 'region' },
  { inseeCode: '75', name: 'Nouvelle-Aquitaine', coverageType: 'region' },
  { inseeCode: '76', name: 'Occitanie', coverageType: 'region' },
  { inseeCode: '84', name: 'Auvergne-Rhône-Alpes', coverageType: 'region' },
  { inseeCode: '93', name: "Provence-Alpes-Côte d'Azur", coverageType: 'region' },
  { inseeCode: '94', name: 'Corse', coverageType: 'region' },
  { inseeCode: '01', name: 'Guadeloupe', coverageType: 'region', isOverseas: true },
  { inseeCode: '02', name: 'Martinique', coverageType: 'region', isOverseas: true },
  { inseeCode: '03', name: 'Guyane', coverageType: 'region', isOverseas: true },
  { inseeCode: '04', name: 'La Réunion', coverageType: 'region', isOverseas: true },
  { inseeCode: '06', name: 'Mayotte', coverageType: 'region', isOverseas: true },
  // Overseas collectivities (COM), modelled as regions to match source data.
  { inseeCode: '975', name: 'Saint-Pierre-Et-Miquelon', coverageType: 'region', isOverseas: true },
  { inseeCode: '977', name: 'Saint-Barthélemy', coverageType: 'region', isOverseas: true },
  { inseeCode: '978', name: 'Saint-Martin', coverageType: 'region', isOverseas: true },
  { inseeCode: '984', name: 'Terres australes et antarctiques françaises', coverageType: 'region', isOverseas: true },
  { inseeCode: '986', name: 'Wallis et Futuna', coverageType: 'region', isOverseas: true },
  { inseeCode: '987', name: 'Polynésie française', coverageType: 'region', isOverseas: true },
  { inseeCode: '988', name: 'Nouvelle-Calédonie', coverageType: 'region', isOverseas: true },
]

export const DEPARTEMENTS: GeographicAreaFixture[] = [
  { inseeCode: '01', name: 'Ain', coverageType: 'departement', parentInseeCode: '84' },
  { inseeCode: '02', name: 'Aisne', coverageType: 'departement', parentInseeCode: '32' },
  { inseeCode: '03', name: 'Allier', coverageType: 'departement', parentInseeCode: '84' },
  { inseeCode: '04', name: 'Alpes-de-Haute-Provence', coverageType: 'departement', parentInseeCode: '93' },
  { inseeCode: '05', name: 'Hautes-Alpes', coverageType: 'departement', parentInseeCode: '93' },
  { inseeCode: '06', name: 'Alpes-Maritimes', coverageType: 'departement', parentInseeCode: '93' },
  { inseeCode: '07', name: 'Ardèche', coverageType: 'departement', parentInseeCode: '84' },
  { inseeCode: '08', name: 'Ardennes', coverageType: 'departement', parentInseeCode: '44' },
  { inseeCode: '09', name: 'Ariège', coverageType: 'departement', parentInseeCode: '76' },
  { inseeCode: '10', name: 'Aube', coverageType: 'departement', parentInseeCode: '44' },
  { inseeCode: '11', name: 'Aude', coverageType: 'departement', parentInseeCode: '76' },
  { inseeCode: '12', name: 'Aveyron', coverageType: 'departement', parentInseeCode: '76' },
  { inseeCode: '13', name: 'Bouches-du-Rhône', coverageType: 'departement', parentInseeCode: '93' },
  { inseeCode: '14', name: 'Calvados', coverageType: 'departement', parentInseeCode: '28' },
  { inseeCode: '15', name: 'Cantal', coverageType: 'departement', parentInseeCode: '84' },
  { inseeCode: '16', name: 'Charente', coverageType: 'departement', parentInseeCode: '75' },
  { inseeCode: '17', name: 'Charente-Maritime', coverageType: 'departement', parentInseeCode: '75' },
  { inseeCode: '18', name: 'Cher', coverageType: 'departement', parentInseeCode: '24' },
  { inseeCode: '19', name: 'Corrèze', coverageType: 'departement', parentInseeCode: '75' },
  { inseeCode: '2A', name: 'Corse-du-Sud', coverageType: 'departement', parentInseeCode: '94' },
  { inseeCode: '2B', name: 'Haute-Corse', coverageType: 'departement', parentInseeCode: '94' },
  { inseeCode: '21', name: "Côte-d'Or", coverageType: 'departement', parentInseeCode: '27' },
  { inseeCode: '22', name: "Côtes-d'Armor", coverageType: 'departement', parentInseeCode: '53' },
  { inseeCode: '23', name: 'Creuse', coverageType: 'departement', parentInseeCode: '75' },
  { inseeCode: '24', name: 'Dordogne', coverageType: 'departement', parentInseeCode: '75' },
  { inseeCode: '25', name: 'Doubs', coverageType: 'departement', parentInseeCode: '27' },
  { inseeCode: '26', name: 'Drôme', coverageType: 'departement', parentInseeCode: '84' },
  { inseeCode: '27', name: 'Eure', coverageType: 'departement', parentInseeCode: '28' },
  { inseeCode: '28', name: 'Eure-et-Loir', coverageType: 'departement', parentInseeCode: '24' },
  { inseeCode: '29', name: 'Finistère', coverageType: 'departement', parentInseeCode: '53' },
  { inseeCode: '30', name: 'Gard', coverageType: 'departement', parentInseeCode: '76' },
  { inseeCode: '31', name: 'Haute-Garonne', coverageType: 'departement', parentInseeCode: '76' },
  { inseeCode: '32', name: 'Gers', coverageType: 'departement', parentInseeCode: '76' },
  { inseeCode: '33', name: 'Gironde', coverageType: 'departement', parentInseeCode: '75' },
  { inseeCode: '34', name: 'Hérault', coverageType: 'departement', parentInseeCode: '76' },
  { inseeCode: '35', name: 'Ille-et-Vilaine', coverageType: 'departement', parentInseeCode: '53' },
  { inseeCode: '36', name: 'Indre', coverageType: 'departement', parentInseeCode: '24' },
  { inseeCode: '37', name: 'Indre-et-Loire', coverageType: 'departement', parentInseeCode: '24' },
  { inseeCode: '38', name: 'Isère', coverageType: 'departement', parentInseeCode: '84' },
  { inseeCode: '39', name: 'Jura', coverageType: 'departement', parentInseeCode: '27' },
  { inseeCode: '40', name: 'Landes', coverageType: 'departement', parentInseeCode: '75' },
  { inseeCode: '41', name: 'Loir-et-Cher', coverageType: 'departement', parentInseeCode: '24' },
  { inseeCode: '42', name: 'Loire', coverageType: 'departement', parentInseeCode: '84' },
  { inseeCode: '43', name: 'Haute-Loire', coverageType: 'departement', parentInseeCode: '84' },
  { inseeCode: '44', name: 'Loire-Atlantique', coverageType: 'departement', parentInseeCode: '52' },
  { inseeCode: '45', name: 'Loiret', coverageType: 'departement', parentInseeCode: '24' },
  { inseeCode: '46', name: 'Lot', coverageType: 'departement', parentInseeCode: '76' },
  { inseeCode: '47', name: 'Lot-et-Garonne', coverageType: 'departement', parentInseeCode: '75' },
  { inseeCode: '48', name: 'Lozère', coverageType: 'departement', parentInseeCode: '76' },
  { inseeCode: '49', name: 'Maine-et-Loire', coverageType: 'departement', parentInseeCode: '52' },
  { inseeCode: '50', name: 'Manche', coverageType: 'departement', parentInseeCode: '28' },
  { inseeCode: '51', name: 'Marne', coverageType: 'departement', parentInseeCode: '44' },
  { inseeCode: '52', name: 'Haute-Marne', coverageType: 'departement', parentInseeCode: '44' },
  { inseeCode: '53', name: 'Mayenne', coverageType: 'departement', parentInseeCode: '52' },
  { inseeCode: '54', name: 'Meurthe-et-Moselle', coverageType: 'departement', parentInseeCode: '44' },
  { inseeCode: '55', name: 'Meuse', coverageType: 'departement', parentInseeCode: '44' },
  { inseeCode: '56', name: 'Morbihan', coverageType: 'departement', parentInseeCode: '53' },
  { inseeCode: '57', name: 'Moselle', coverageType: 'departement', parentInseeCode: '44' },
  { inseeCode: '58', name: 'Nièvre', coverageType: 'departement', parentInseeCode: '27' },
  { inseeCode: '59', name: 'Nord', coverageType: 'departement', parentInseeCode: '32' },
  { inseeCode: '60', name: 'Oise', coverageType: 'departement', parentInseeCode: '32' },
  { inseeCode: '61', name: 'Orne', coverageType: 'departement', parentInseeCode: '28' },
  { inseeCode: '62', name: 'Pas-de-Calais', coverageType: 'departement', parentInseeCode: '32' },
  { inseeCode: '63', name: 'Puy-de-Dôme', coverageType: 'departement', parentInseeCode: '84' },
  { inseeCode: '64', name: 'Pyrénées-Atlantiques', coverageType: 'departement', parentInseeCode: '75' },
  { inseeCode: '65', name: 'Hautes-Pyrénées', coverageType: 'departement', parentInseeCode: '76' },
  { inseeCode: '66', name: 'Pyrénées-Orientales', coverageType: 'departement', parentInseeCode: '76' },
  { inseeCode: '67', name: 'Bas-Rhin', coverageType: 'departement', parentInseeCode: '44' },
  { inseeCode: '68', name: 'Haut-Rhin', coverageType: 'departement', parentInseeCode: '44' },
  { inseeCode: '69', name: 'Rhône', coverageType: 'departement', parentInseeCode: '84' },
  { inseeCode: '70', name: 'Haute-Saône', coverageType: 'departement', parentInseeCode: '27' },
  { inseeCode: '71', name: 'Saône-et-Loire', coverageType: 'departement', parentInseeCode: '27' },
  { inseeCode: '72', name: 'Sarthe', coverageType: 'departement', parentInseeCode: '52' },
  { inseeCode: '73', name: 'Savoie', coverageType: 'departement', parentInseeCode: '84' },
  { inseeCode: '74', name: 'Haute-Savoie', coverageType: 'departement', parentInseeCode: '84' },
  { inseeCode: '75', name: 'Paris', coverageType: 'departement', parentInseeCode: '11' },
  { inseeCode: '76', name: 'Seine-Maritime', coverageType: 'departement', parentInseeCode: '28' },
  { inseeCode: '77', name: 'Seine-et-Marne', coverageType: 'departement', parentInseeCode: '11' },
  { inseeCode: '78', name: 'Yvelines', coverageType: 'departement', parentInseeCode: '11' },
  { inseeCode: '79', name: 'Deux-Sèvres', coverageType: 'departement', parentInseeCode: '75' },
  { inseeCode: '80', name: 'Somme', coverageType: 'departement', parentInseeCode: '32' },
  { inseeCode: '81', name: 'Tarn', coverageType: 'departement', parentInseeCode: '76' },
  { inseeCode: '82', name: 'Tarn-et-Garonne', coverageType: 'departement', parentInseeCode: '76' },
  { inseeCode: '83', name: 'Var', coverageType: 'departement', parentInseeCode: '93' },
  { inseeCode: '84', name: 'Vaucluse', coverageType: 'departement', parentInseeCode: '93' },
  { inseeCode: '85', name: 'Vendée', coverageType: 'departement', parentInseeCode: '52' },
  { inseeCode: '86', name: 'Vienne', coverageType: 'departement', parentInseeCode: '75' },
  { inseeCode: '87', name: 'Haute-Vienne', coverageType: 'departement', parentInseeCode: '75' },
  { inseeCode: '88', name: 'Vosges', coverageType: 'departement', parentInseeCode: '44' },
  { inseeCode: '89', name: 'Yonne', coverageType: 'departement', parentInseeCode: '27' },
  { inseeCode: '90', name: 'Territoire de Belfort', coverageType: 'departement', parentInseeCode: '27' },
  { inseeCode: '91', name: 'Essonne', coverageType: 'departement', parentInseeCode: '11' },
  { inseeCode: '92', name: 'Hauts-de-Seine', coverageType: 'departement', parentInseeCode: '11' },
  { inseeCode: '93', name: 'Seine-Saint-Denis', coverageType: 'departement', parentInseeCode: '11' },
  { inseeCode: '94', name: 'Val-de-Marne', coverageType: 'departement', parentInseeCode: '11' },
  { inseeCode: '95', name: "Val-d'Oise", coverageType: 'departement', parentInseeCode: '11' },
  { inseeCode: '971', name: 'Guadeloupe', coverageType: 'departement', parentInseeCode: '01', isOverseas: true },
  { inseeCode: '972', name: 'Martinique', coverageType: 'departement', parentInseeCode: '02', isOverseas: true },
  { inseeCode: '973', name: 'Guyane', coverageType: 'departement', parentInseeCode: '03', isOverseas: true },
  { inseeCode: '974', name: 'La Réunion', coverageType: 'departement', parentInseeCode: '04', isOverseas: true },
  { inseeCode: '976', name: 'Mayotte', coverageType: 'departement', parentInseeCode: '06', isOverseas: true },
]
